### ISSUE TITLE
Coverage report is not displayed in comment

### ISSUE THREAD

**Issue by upgundecha** [raulanatol/jest-coverage-comment-action#14]
Hi, trying to use this action in my workflow. I can see overall coverage% in the comment but the coverage report is not displayed

![image](https://user-images.githubusercontent.com/1009929/122954236-d9b32300-d3b1-11eb-8c7f-48c75f28cd6e.png)

Status from console

![image](https://user-images.githubusercontent.com/1009929/122954374-f5b6c480-d3b1-11eb-8a96-0d0dd3b39db6.png)

**Comment by raulanatol** [comment]
@upgundecha thanks for your feedback :D

I've close a new release with this fix.
https://github.com/raulanatol/jest-coverage-comment-action/releases/tag/v1.1.2

**Comment by upgundecha** [comment]
Thank you @raulanatol
