### ISSUE TITLE
Bug - No coverage report found!

### ISSUE THREAD

**Issue by raulanatol** [raulanatol/jest-coverage-comment-action#17]
<img width="998" alt="CleanShot 2021-07-23 at 09 30 24@2x" src="https://user-images.githubusercontent.com/2389019/126756746-31f488f0-15bb-4bd8-b985-d68df0a948ac.png">

**Comment by MishaKav** [comment]
I find the solution in a similar package
https://github.com/marketplace/actions/jest-coverage-comment
